name: 手動觸發的自動化

on:
    workflow_dispatch:

jobs:
    automation:
        name: 自動化
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Merge Secrets
              run: node merge.js
              env:
                  config: config.yml
                  secrets: ${{ secrets.SECRETS }}
                  
            - name: install webkit
              run: npx playwright install webkit --with-deps

            - name: Bahamut Automation
              run: npx bahamut-automation -c merged-config.yml

            - uses: gautamkrishnar/keepalive-workflow@master
