name: 每天的自動化

on:
    schedule:
        - cron: "20 4,16 * * *"

jobs:
    automation:
        name: 自動化
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Merge Secrets
              run: node merge.js
              env:
                  config: config.yml
                  secrets: ${{ secrets.SECRETS }}
                  
            - name: install webkit
              run: npx playwright install webkit --with-deps

            - name: Bahamut Automation
              run: docker run --rm -v "$(pwd)/merged-config.yml:/config.yml" jacoblincool/bahamut-automation

            - uses: gautamkrishnar/keepalive-workflow@master
